#!/usr/bin/env python3
"""
Generate Mini-GNN grid search submission file from mini_gnn_grid.yml.

Reads grid_params (lists) and fixed_params from the YAML, computes the
Cartesian product, and rewrites jobs/mini_gnn_grid_search.sub with a
'queue ... from (...)' block.

Usage:
    python generate_mini_gnn_grid_search.py
"""

import itertools
from pathlib import Path

import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
PIPELINE_ROOT = SCRIPT_DIR.parent
JOBS_DIR = Path("/data/alice/bkuipers/jobs")

GRID_CONFIG = (
    PIPELINE_ROOT
    / "acorn_configs"
    / "track_building_stage_(3)"
    / "mini_gnn_grid.yml"
)
SUB_FILE = JOBS_DIR / "mini_gnn_grid_search.sub"

# Parameters passed as --set overrides (order matches shell script positional args)
GRID_KEYS = ["hidden_dim", "n_layers", "emb_dim", "dropout", "proj_layers", "temperature", "lr"]


def expand_grid(grid_params):
    names = list(grid_params.keys())
    values = [
        v if isinstance(v, list) else [v]
        for v in grid_params.values()
    ]
    return [dict(zip(names, combo)) for combo in itertools.product(*values)]


def make_run_name(combo):
    return (
        f"h{combo['hidden_dim']}_l{combo['n_layers']}_e{combo['emb_dim']}"
        f"_d{combo['dropout']}_pl{combo['proj_layers']}"
        f"_t{combo['temperature']}_lr{combo['lr']}"
    )


def resource_lines(job_type: str, job_category: str) -> str:
    """Return HTCondor resource request lines for the given job type."""
    if job_type == "gpu":
        cpus, memory, gpu_line = 8, "16G", "request_gpus            = 1\n"
    else:  # cpu
        cpus, memory, gpu_line = 4, "16G", ""
    return (
        f'+UseOS                  = "el9"\n'
        f'+JobCategory            = "{job_category}"\n'
        f'{gpu_line}'
        f'request_cpus            = {cpus}\n'
        f'request_memory          = {memory}'
    )


def write_sub_file(combos, job_type, job_category):
    rows = "\n".join(
        "  " + ", ".join(str(c[k]) for k in GRID_KEYS)
        for c in combos
    )
    col_header = ", ".join(GRID_KEYS)
    name_pattern = "h$(hidden_dim)_l$(n_layers)_e$(emb_dim)_d$(dropout)_pl$(proj_layers)_t$(temperature)_lr$(lr)"

    config_path = str(GRID_CONFIG)

    content = f"""\
#!/usr/bin/env condor_submit
# Mini-GNN Grid Search — auto-generated by generate_mini_gnn_grid_search.py
# Edit acorn_configs/track_building_stage_(3)/mini_gnn_grid.yml, then re-run the generator.
# {len(combos)} combination(s)  |  job_type={job_type}  job_category={job_category}

executable              = run_mini_gnn_grid.sh
arguments               = $(hidden_dim) $(n_layers) $(emb_dim) $(dropout) $(proj_layers) $(temperature) $(lr) {config_path}
log                     = /data/alice/bkuipers/jobs/output/mini_gnn_grid_{name_pattern}_$(ClusterId).log
output                  = /data/alice/bkuipers/jobs/output/mini_gnn_grid_{name_pattern}_$(ClusterId).out
error                   = /data/alice/bkuipers/jobs/output/mini_gnn_grid_{name_pattern}_$(ClusterId).err

{resource_lines(job_type, job_category)}

should_transfer_files   = NO
initialdir              = /data/alice/bkuipers/low_pt_gnn_pipeline

environment             = "CONDA_ENV=acorn"

# ── Grid combinations ─────────────────────────────────────────────────────────
# Columns: {col_header}
queue {col_header} from (
{rows}
)
"""
    SUB_FILE.write_text(content)


def main():
    with open(GRID_CONFIG) as f:
        spec = yaml.safe_load(f)

    grid_params = spec.get("grid_params", {})
    fixed_params = spec.get("fixed_params", {})
    grid_subset = {k: grid_params[k] for k in GRID_KEYS if k in grid_params}
    combos = expand_grid(grid_subset)

    job_type = fixed_params.get("job_type", "gpu")
    job_category = fixed_params.get("job_category", "medium")

    print(f"Grid: {len(combos)} combination(s)  |  job_type={job_type}  job_category={job_category}")
    for c in combos:
        print(f"  {make_run_name(c)}")
    print()

    JOBS_DIR.mkdir(exist_ok=True)
    (JOBS_DIR / "output").mkdir(exist_ok=True)
    write_sub_file(combos, job_type, job_category)
    print(f"Written: {SUB_FILE}")
    print()
    print("To submit all jobs:")
    print(f"  cd {JOBS_DIR}")
    print(f"  condor_submit {SUB_FILE.name}")


if __name__ == "__main__":
    main()
