input_dir: /data/alice/bkuipers/low_pt_gnn_pipeline/data/graph_constructed_latent
stage_dir: /data/alice/bkuipers/low_pt_gnn_pipeline/data/gnn_stage
data_split:
- 10000
- 500
- 1000
project: GNN_gridsearch_300_mixed_one_in_one_out
use_wandb: true
wandb_entity: bart_kuipers-nikhef
wandb_log_every_n_batches: 50
accelerator: cuda
devices: 1
nodes: 1
precision: 16-mixed
edge_cut: 0.5
undirected: true
undirected_message_passing: true
node_features:
- hit_r
- hit_phi
- hit_z
node_scales:
- 1000
- 3.14159265359
- 500
layernorm: true
batchnorm: true
num_workers:
- 8
- 8
- 0
max_epochs: 15
scheduler: ReduceLROnPlateau
factor: 0.8
early_stopping_patience: 6
check_val_every_n_epoch: 1
val_check_interval: 0.5
accumulate_grad_batches: 1
pos_weight: 1
logger: false
hidden: 256
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
lr: 0.001
warmup: 1
patience: 0
aggregation:
- sum
- mean
- max
- std
hidden_activation: SiLU
output_activation: Tanh
run_name: h256_gi8_nl3_el3_lr0.001_agg-sum-mean-max-std_act-SiLU-Tanh
node_net_recurrent: true
edge_net_recurrent: true
track_running_stats: false
