# GNN Hyperparameter Grid Search Configuration
# 
# Usage:    python generate_grid_search.py
#

# Grid search parameters (lists = grid, single values = fixed)
grid_params:
  # Architecture
  hidden: [256]  # Hidden layer size.  256
  n_graph_iters: [8]
  nb_node_layer: [3]  # 3
  nb_edge_layer: [3]  # 3
  
  # Training  
  lr: [0.001]  # Learning rate            
  warmup: [1]
  patience: [0]           # for lr decay
  
  # Aggregation
  aggregation:
    - [sum, mean, max, std]  
   # Aggregation functions for node updates


  # Activations
  hidden_activation: [SiLU]
  output_activation: [Tanh]

# Fixed parameters (applied to all runs)
fixed_params:
  # Data
  input_dir: data/graph_constructed_latent_tsmear_25ps
  stage_dir: data/gnn_stage/
  data_split: [10000, 500, 1000]

  # W&B
  project: GNN_gridsearch_400_pions
  use_wandb: true
  wandb_entity: bart_kuipers-nikhef
  wandb_log_every_n_batches: 50
  
  # Hardware
  accelerator: cuda
  devices: 1
  nodes: 1
  precision: "16-mixed"
  
  # Model
  edge_cut: 0.5
  undirected: true
  undirected_message_passing: true

  node_features: [hit_r, hit_phi, hit_z, hit_t_smeared, hit_has_time]
  node_scales: [1000, 3.14159265359, 500, 4000, 1]

  # node_features: [hit_r, hit_phi, hit_z]      # 3D features (without time)
  # ode_scales: [1000, 3.14159265359, 500]                # Scales for [r, phi, z, t]
  # node_features: [hit_r, hit_phi, hit_z, hit_t]      # 3D features (without time)
  # node_scales: [1000, 3.14, 499, 2000]                # Scales for [r, phi, z, t]
  
  layernorm: true
  batchnorm: true
  
  # Training
  num_workers: [8, 8, 0]
  max_epochs: 15
  scheduler: ReduceLROnPlateau
  factor: 0.8
  early_stopping_patience: 6

  #log_every_n_steps: 1
  check_val_every_n_epoch: 1

  val_check_interval: 0.5            #note 1 does batch =1 , 1.0 does epoch = 1, 0.2 does 20% of an epoch
  accumulate_grad_batches: 1

  pos_weight: 1
  logger: false


  #   # Training
  # num_workers: [8, 8, 0]
  # max_epochs: 50
  # scheduler: ReduceLROnPlateau
  # factor: 0.5
  # early_stopping_patience: 4
  # log_every_n_steps: 1
  # check_val_every_n_epoch: 1
  # val_check_interval: 0.2
  # accumulate_grad_batches: 1
  # pos_weight: 1
  # logger: false

